version: 2
updates:
- package-ecosystem: bundler
  directory: "/"
  schedule:
    interval: daily
    time: "03:00"
    timezone: Europe/London
  open-pull-requests-limit: 10
  reviewers:
  - tomas-stefano
  - brenetic
  - mattempty
  - njseeto
  ignore:
  - dependency-name: rubocop
    versions:
    - 1.12.0
    - 1.12.1
    - 1.9.0
  - dependency-name: rails
    versions:
    - 6.1.1
    - 6.1.2
    - 6.1.2.1
    - 6.1.3
  - dependency-name: rspec-rails
    versions:
    - 4.1.0
    - 4.1.1
    - 5.0.0
  - dependency-name: database_cleaner
    versions:
    - 1.99.0
    - 2.0.0
  - dependency-name: capybara
    versions:
    - 3.35.2
- package-ecosystem: docker
  directory: "/docker/web"
  schedule:
    interval: daily
    time: "03:00"
    timezone: Europe/London
  open-pull-requests-limit: 10
  reviewers:
  - tomas-stefano
  - brenetic
  - mattempty
  - njseeto
  ignore:
  - dependency-name: ruby
    versions:
    - 3.0.0.pre.buster
    - 3.0.1.pre.buster
- package-ecosystem: docker
  directory: "/docker/worker"
  schedule:
    interval: daily
    time: "03:00"
    timezone: Europe/London
  open-pull-requests-limit: 10
  reviewers:
  - tomas-stefano
  - brenetic
  - mattempty
  - njseeto
  ignore:
  - dependency-name: ruby
    versions:
    - 3.0.0.pre.buster
    - 3.0.1.pre.buster
