language: ruby

addons:
  postgresql: "10.3"
  apt:
    packages:
    - postgresql-10
    - postgresql-client-10
services:
  - postgresql

rvm:
    - 2.5.1

script:
    - bundle exec rails db:reset db:setup db:migrate RAILS_ENV=test
    - bundle exec rspec

env:
  global:
  - PGPORT=5433
