version: 2
jobs:
  test:
    working_directory: ~/circle
    docker:
      - image: $AWS_BUILD_IMAGE_ECR_ACCOUNT_URL
        aws_auth:
          aws_access_key_id: $AWS_BUILD_IMAGE_ACCESS_KEY_ID
          aws_secret_access_key: $AWS_BUILD_IMAGE_SECRET_ACCESS_KEY
        environment:
          RAILS_ENV: test
          PGHOST: 127.0.0.1
          PGUSER: root
          DATABASE_URL: postgresql://root@localhost/fb-publisher_test
      - image: circleci/postgres:10.6-alpine-ram
        environment:
          POSTGRES_USER: root
          POSTGRES_DB: circle-test_test
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: test
          command: 'make spec'
  build_and_deploy_to_test:
    working_directory: ~/circle/git/fb-publisher
    docker: &ecr_base_image
      - image: $AWS_BUILD_IMAGE_ECR_ACCOUNT_URL
        aws_auth:
          aws_access_key_id: $AWS_BUILD_IMAGE_ACCESS_KEY_ID
          aws_secret_access_key: $AWS_BUILD_IMAGE_SECRET_ACCESS_KEY
    steps:
      - checkout
      - setup_remote_docker
      - add_ssh_keys:
          fingerprints:
            - "05:0e:96:bc:58:f9:60:cc:b6:34:cb:f5:05:91:2c:11"
      - run:
          name: Setup base environment variable
          command: |
            echo "export BUILD_SHA=$CIRCLE_SHA1" >> $BASH_ENV
            echo "export SSH_FILE_FOR_SECRETS=~/.ssh/id_rsa_050e96bc58f960ccb634cbf505912c11" >> $BASH_ENV
      - run:
          name: cloning deploy scripts
          command: 'git clone git@github.com:ministryofjustice/fb-deploy.git deploy-scripts'
      - run:
          name: build and push docker images
          environment:
            ENVIRONMENT_NAME: test
          command: './deploy-scripts/bin/build'
      - run:
          name: deploy to test
          environment:
            APPLICATION_NAME: fb-publisher
            PLATFORM_ENV: test
            K8S_NAMESPACE: formbuilder-publisher-test
          command: './deploy-scripts/bin/deploy'
  build_and_deploy_to_live:
    working_directory: ~/circle/git/fb-publisher
    docker: *ecr_base_image
    steps:
      - checkout
      - setup_remote_docker
      - add_ssh_keys:
          fingerprints:
            - "05:0e:96:bc:58:f9:60:cc:b6:34:cb:f5:05:91:2c:11"
      - run:
          name: Setup base environment variable
          command: |
            echo "export BUILD_SHA=$CIRCLE_SHA1" >> $BASH_ENV
            echo "export SSH_FILE_FOR_SECRETS=~/.ssh/id_rsa_050e96bc58f960ccb634cbf505912c11" >> $BASH_ENV
      - run:
          name: cloning deploy scripts
          command: 'git clone git@github.com:ministryofjustice/fb-deploy.git deploy-scripts'
      - run:
          name: build and push docker images
          environment:
            ENVIRONMENT_NAME: live
          command: './deploy-scripts/bin/build'
      - run:
          name: deploy to live
          environment:
            APPLICATION_NAME: fb-publisher
            PLATFORM_ENV: live
            K8S_NAMESPACE: formbuilder-publisher-live
          command: './deploy-scripts/bin/deploy'

workflows:
  version: 2
  test_and_build:
    jobs:
      - test
      - build_and_deploy_to_test:
          requires:
            - test
          filters:
            branches:
              only: master
      - confirm_live_deploy:
          type: approval
          requires:
            - build_and_deploy_to_test
      - build_and_deploy_to_live:
          requires:
            - confirm_live_deploy
