apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: "fb-publisher-ing-{{ .Values.environmentName }}"
spec:
  tls:
  - hosts:
    - fb-publisher-{{ .Values.environmentName }}.apps.live-1.cloud-platform.service.justice.gov.uk
  rules:
  - host: fb-publisher-{{ .Values.environmentName }}.apps.live-1.cloud-platform.service.justice.gov.uk
    http:
      paths:
      - path: /
        backend:
          serviceName: fb-publisher-svc-{{ .Values.environmentName }}
          servicePort: 80
