apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: "fb-publisher-ing-{{ .Values.environmentName }}"
  annotations:
    external-dns.alpha.kubernetes.io/set-identifier: "fb-publisher-ing-{{ .Values.environmentName }}-formbuilder-publisher-{{ .Values.environmentName }}-blue"
    external-dns.alpha.kubernetes.io/aws-weight: "0"
spec:
  tls:
  - hosts:
    - fb-publisher-{{ .Values.environmentName }}.apps.live-1.cloud-platform.service.justice.gov.uk
  rules:
  - host: fb-publisher-{{ .Values.environmentName }}.apps.live-1.cloud-platform.service.justice.gov.uk
    http:
      paths:
      - path: /
        backend:
          serviceName: fb-publisher-svc-{{ .Values.environmentName }}
          servicePort: 80
