apiVersion: v1
kind: Secret
metadata:
  name: fb-publisher-app-secrets-{{ .Values.environmentName }}
type: Opaque
data:
  auth0_client_id: {{ .Values.auth0_client_id }}
  auth0_client_secret: {{ .Values.auth0_client_secret }}
  secret_key_base: {{ .Values.secret_key_base }}
